-- DATETIME and TIMESTAMP they are data types to store date into it. 
-- The difference between then is the size of stored data. 
-- DATATIME has a wider range and a high memory cost to store on it. 
-- TIMESTAMP has both a lower range and data size, 
	-- making it better if you needs to care about memory.