CREATE TABLE tweets(
	content VARCHAR(255) NOT NULL,
    user VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP,
    id INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(id)
);